name: connectapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+8
environment:
  # sdk: ^3.6.0
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.3.5
  fluttertoast: ^8.2.10
  get: ^4.6.6
  image_picker: ^1.1.2
  getwidget: ^7.0.0
  intl: ^0.20.2
  flutter_check_box_rounded: ^3.3.0
  phosphor_flutter: ^2.1.0
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  get_storage: ^2.1.1
  package_info_plus: ^8.3.0
  cached_network_image: ^3.4.1
  chewie: ^1.11.3
  video_player: ^2.10.0
  daily_flutter: ^0.31.0
  url_launcher: ^6.3.1
  socket_io_client: ^3.1.2
  flutter_local_notifications: ^19.2.1
  flutter_stripe: ^11.5.0
  share_plus: ^11.0.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.4
  file_picker: ^10.2.0
  fl_chart: ^0.71.0
  flutter_slidable: ^4.0.1
  flutter_inappwebview: ^6.1.5
  audioplayers: ^6.5.0
  record: ^6.0.0
  workmanager: ^0.6.0
  google_sign_in: ^6.1.5
  flutter_web_auth: ^0.6.0
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  flutter_html: ^3.0.0
  flutter_svg: ^2.2.0
  google_maps_flutter: ^2.12.3
  flutter_map: ^8.1.1
  latlng: ^2.0.7
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.0
  webview_flutter_wkwebview: ^3.23.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  app_settings: ^6.1.1
  carousel_slider: ^5.1.1
  flutter_secure_storage: ^9.2.4
  model_viewer_plus: ^1.9.2
  cache_manager_plus: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  readmore: ^3.0.0
  font_awesome_flutter: ^10.9.1
  flutter_launcher_icons: ^0.14.4
  app_links: ^3.5.0
  flutter_app_badger: ^1.3.0
  uni_links: ^0.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon/appicon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: helveticaLight
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.otf
    - family: helveticaMedium
      fonts:
        - asset: assets/fonts/HelveticaNeue-Medium.otf
